name: Needs More Info
on:
  issues:
    types: [opened]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'JacksonKearl/vscode-triage-github-actions'
          ref: master # todo: change to tags once stabalized
      - name: Run Needs More Info
        uses: ./needs-more-info
        with:
          matcher: '((vs ?code|version)\W*:?\W*v?\W*\d\.\d\d(\.\d)?)|insiders'
          label: needs more info
