name: CI

on:
  push:
    branches:
      - '**'

jobs:
  stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Package VSIX
        run: |
          VSIX="test-${GITHUB_SHA:0:8}.txt"
          echo test > $VSIX
          echo "VSIX=$VSIX" | tee -a $GITHUB_ENV
      - name: Store VSIX
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.VSIX }}
          path: ${{ env.VSIX }}
